/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-hackrf_sync
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_HACKRF_SYNC_API_H
#define INCLUDED_HACKRF_SYNC_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_hackrf_sync_EXPORTS
#define HACKRF_SYNC_API __GR_ATTR_EXPORT
#else
#define HACKRF_SYNC_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_HACKRF_SYNC_API_H */
